# Generated by Django 4.2.9 on 2024-01-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name_alter_amenity_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='onwer',
            new_name='owner',
        ),
    ]
