# Generated by Django 4.2.9 on 2024-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_amenity_options_rename_onwer_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='country',
            field=models.CharField(default='한국', max_length=50),
        ),
    ]
