# Generated by Django 4.2.9 on 2024-01-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
        ('rooms', '0004_room_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catagories.category'),
        ),
    ]
