# Generated by Django 4.2.9 on 2024-01-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
        ('experiences', '0002_remove_perk_detail_perk_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catagories.category'),
        ),
    ]
