# Generated by Django 4.2.9 on 2024-01-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='expoerience',
            new_name='experience',
        ),
    ]
